libname ag '/lustre/scr/v/i/victorw/ag/snplst';
%let sect= &sysparm.;

proc sort data=ag.agp&sect. out=temp; by iid; run;
data temp;
  merge temp(in=t) ag.ag500kmad;
  by iid;
  if t;
run;
proc sort data=temp; by pair iid; run;
proc transpose data=temp out=tempt; 
  by pair iid;
  var ss:;
run;
proc sort data=tempt; by _NAME_; run;
data tempt;
  merge tempt ag.mx_gwmp;
  by _NAME_;
run;
proc sort data=tempt; by pair; run;
proc mixed data=tempt method=ml noitprint noclprint ratio covtest; 
      by pair;
	  where estimate>=0;
      class _NAME_; 
      model COL1=/s notest;
      repeated /type=ar(1) subject=_NAME_; 
      ods output CovParms=ag.pmxagmadp&sect.; 
run;
proc mixed data=tempt method=ml noitprint noclprint ratio covtest; 
      by pair;
	  where estimate<0;
      class _NAME_; 
      model COL1=/s notest;
      repeated /type=ar(1) subject=_NAME_; 
      ods output CovParms=ag.nmxagmadp&sect.; 
run;
