libname ag '/lustre/scr/v/i/victorw/ag/snplst';
libname agpa '/lustre/scr/v/i/victorw/ag/palst';
libname agat '/lustre/scr/v/i/victorw/ag/agat';
%let sect= &sysparm.;

proc sort data=agpa.agconpa&sect. out=temp; by iid; run;
data tempm;
  merge temp(in=t) ag.ag500kconmad;
  by iid;
  if t;
run;
proc sort data=tempm; by pair ipid; run;
proc transpose data=tempm out=tempm; 
  by pair;
  var ss:;
run;
data tempm(keep=pair _NAME_ colc1 colc2 colc3 colc4 colc5 colc6);
  set tempm;
  colc1=.; colc2=.; colc3=.; colc4=.; colc5=.; colc6=.;
  if col1=0 & col2=0 then do;
    colc1=4; colc2=4; colc3=3; colc4=3; colc5=2; colc6=2;
  end;
  else if (col1=0 & col2=1) or (col1=1 & col2=0) then do;
    colc1=2; colc2=3; colc3=2; colc4=4; colc5=3; colc6=4;
  end;
  else if col1=1 & col2=1 then do;
    colc1=3; colc2=2; colc3=4; colc4=2; colc5=4; colc6=3;
  end;
  else if (col1=2 & col2=1) or (col1=1 & col2=2) then do;
    colc1=5; colc2=5; colc3=5; colc4=5; colc5=5; colc6=5;
  end;
  else if (col1=0 & col2=2) or (col1=2 & col2=0) then do;
    colc1=1; colc2=1; colc3=1; colc4=1; colc5=1; colc6=1;
  end;
  else if col1=2 & col2=2 then do;
    colc1=6; colc2=6; colc3=6; colc4=6; colc5=6; colc6=6;
  end;
  if colc1=. then delete;
run;
%MACRO seg(num);
%do i=1 %to &num.;
proc sort data=tempm; by pair colc&i.; run;
data tempm med(keep=pair _NAME_ coln);
  set tempm;
  retain coln 0;
  by pair colc&i.;
  if first.pair then coln=0;
  coln=coln+1;
  output tempm;
  if last.pair then output med;
run;
data med; set med; coln=coln/2; run;
data tempm(keep=pair _NAME_ colc1-colc6);
  merge tempm med(rename=(coln=med));
  by pair;
  if coln=<med then colc&i.=0;
  else if coln>med then colc&i.=1;
run;
%end;
%MEND;
%seg(6);
proc sort data=tempm; by pair _NAME_; run;
data tempr;
  merge temp(in=t) ag.ag500kr;
  by iid;
  if t;
run;
proc sort data=tempr; by pair ipid; run;
proc transpose data=tempr out=tempr; 
  by pair;
  var ss:;
run;
proc sort data=tempr; by pair _NAME_; run;
proc transpose data=tempr out=tempr; 
  by pair _NAME_;
  var col1 col2;
run;
data tempr;
  merge tempr tempm(in=t);
  by pair _NAME_;
  if t;
run;
%MACRO seg(num);
%do i=1 %to &num.;
proc sort data=tempr; by pair colc&i.; run;
ods listing close;
proc mixed data=tempr method=ml noitprint noclprint ratio covtest; 
  class pair _NAME_; 
  by pair colc&i.;
  model col1=/s notest;
  repeated /type=ar(1) subject=_NAME_; 
  ods output CovParms=agat.mx_agconmed&i.at&sect.; 
run;
ods listing;
%end;
%MEND;
%seg(6);
