libname ag '/lustre/scr/v/i/victorw/ag/snplst';
libname agp '/lustre/scr/v/i/victorw/ag/plst';
libname ag200 '/lustre/scr/v/i/victorw/ag/200';
*libname ag "D:/AM/FHS550k/agcon";
*libname agp "D:/AM/FHS550k/agcon/plst";
%let sect= &sysparm.;

proc sort data=agp.agcon200p&sect. out=temp; by iid; run;
data tempm;
  merge temp(in=t) ag.ag500kconmad;
  by iid;
  if t;
run;
proc sort data=tempm; by pair ipid; run;
proc transpose data=tempm out=tempm; 
  by pair;
  var ss:;
run;
data tempm(keep=pair _NAME_ col);
  set tempm;
  col=.;
  if col1=0 & col2=0 then col=4;
  else if col1=1 & col2=1 then col=3;
  else if col1=2 & col2=2 then col=6;
  else if col1=0 & col2=1 then col=2;
  else if col1=1 & col2=0 then col=2;
  else if col1=0 & col2=2 then col=1;
  else if col1=2 & col2=0 then col=1;
  else if col1=2 & col2=1 then col=5;
  else if col1=1 & col2=2 then col=5;
  if col=. then delete;
run;
proc sort data=tempm; by pair col; run;
data tempm med(keep=pair _NAME_ coln);
  set tempm;
  retain coln 0;
  by pair col;
  if first.pair then coln=0;
  coln=coln+1;
  output tempm;
  if last.pair then output med;
run;
data med; set med; coln=coln/2; run;
data tempm(keep=pair _NAME_ col);
  merge tempm med(rename=(coln=med));
  by pair;
  if coln=<med then col=0;
  else if coln>med then col=1;
run;
proc sort data=tempm; by pair _NAME_; run;
data tempr;
  merge temp(in=t) ag.ag500kr;
  by iid;
  if t;
run;
proc sort data=tempr; by pair ipid; run;
proc transpose data=tempr out=tempr; 
  by pair;
  var ss:;
run;
proc sort data=tempr; by pair _NAME_; run;
proc transpose data=tempr out=tempr; 
  by pair _NAME_;
  var col1 col2;
run;
data tempr;
  merge tempr tempm(in=t);
  by pair _NAME_;
  if t;
run;
proc sort data=tempr; by pair col; run;
ods listing close;
proc mixed data=tempr method=ml noitprint noclprint ratio covtest; 
  class pair _NAME_; 
  by pair col;
  model col1=/s notest;
  repeated /type=ar(1) subject=_NAME_; 
  ods output CovParms=ag200.mx_agconmed&sect.; 
run;
ods listing;
