libname ag '/lustre/scr/v/i/victorw/ag/snplst';
libname agt '/lustre/scr/h/e/hexuanl/ag';

proc sort data=agt.trblrp out=temp; by iid; run;
data temp;
  merge temp(in=t) ag.ag500kconmad;
  by iid;
  if t;
run;
proc sort data=temp; by pair ipid; run;
proc transpose data=temp out=tempt; 
  by pair ;
  var ss:;
run;
data tempt;
  set tempt;
  col=.;
  if col1=0 & col2=0 then col=4;
  else if (col1=0 & col2=1) or (col1=1 & col2=0) then col=2;
  else if col1=1 & col2=1 then col=3;
  else if (col1=2 & col2=1) or (col1=1 & col2=2) then col=5;
  else if (col1=0 & col2=2) or (col1=2 & col2=0) then col=1;
  else if col1=2 & col2=2 then col=6;
  if col=. then delete;
run;
proc freq data=tempt noprint; 
  by pair; 
  tables col / out=agt.freq; 
run;
proc sort data=agt.freq; by col; run;
proc means data=agt.freq ; 
  class col;
  vars PERCENT; 
run;
