libname ag '/lustre/scr/v/i/victorw/ag/snplst';
libname agp '/lustre/scr/v/i/victorw/ag/plst';
libname agf '/lustre/scr/v/i/victorw/ag/pfreq';

%MACRO seg(num);
%do i=0 %to &num.;
%let sect= %eval(&sysparm.+&i.*100);
proc sort data=agp.agp&sect. out=temp; by iid; run;
data temp;
  merge temp(in=t) ag.ag500km;
  by iid;
  if t;
run;
proc sort data=temp; by pair; run;
proc transpose data=temp out=temp; 
  by pair;
  var ss:;
run;
data temp;
  set temp;
  col=.;
  if col1=0 & col2=0 then col=4;
  else if (col1=0 & col2=1) or (col1=1 & col2=0) then col=2;
  else if col1=1 & col2=1 then col=3;
  else if (col1=2 & col2=1) or (col1=1 & col2=2) then col=5;
  else if (col1=0 & col2=2) or (col1=2 & col2=0) then col=1;
  else if col1=2 & col2=2 then col=6;
  if col=. then delete;
run;
proc freq data=temp noprint; 
  by pair; 
  tables col / out=agf.freq&sect.; 
run;
proc sort data=agf.freq&sect.; by col; run;
%end;
%MEND;
%seg(23);
