ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs3094315_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs3094315_G  '; run;
data mx_all; set mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs6685064_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs6685064_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs3766180_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs3766180_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs7519837_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs7519837_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2272908_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2272908_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs7513222_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs7513222_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs12084736_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs12084736_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2840528_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2840528_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs3736330_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs3736330_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2645081_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2645081_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs7512269_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs7512269_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs10910097_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs10910097_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs3890745_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs3890745_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2817174_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2817174_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2817178_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2817178_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs1798246_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs1798246_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2455144_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2455144_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2500278_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2500278_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4648505_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4648505_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs10910025_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs10910025_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs6663840_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs6663840_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs10909830_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs10909830_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs7519458_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs7519458_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs10915495_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs10915495_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs3935162_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs3935162_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4129100_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4129100_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs10915421_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs10915421_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs12073797_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs12073797_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4233262_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4233262_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2132177_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2132177_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs903540_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs903540_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs7528938_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs7528938_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs693734_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs693734_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs17448695_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs17448695_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs351619_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs351619_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs7418164_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs7418164_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs641473_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs641473_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs639739_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs639739_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs16838800_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs16838800_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs780587_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs780587_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs16839089_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs16839089_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs350171_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs350171_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs705689_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs705689_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs705690_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs705690_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs6703696_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs6703696_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs12092980_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs12092980_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4654556_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4654556_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs241278_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs241278_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs241212_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs241212_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs1541318_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs1541318_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs241225_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs241225_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs12567277_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs12567277_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2101195_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2101195_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs900501_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs900501_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs3947662_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs3947662_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs11587129_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs11587129_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2071995_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2071995_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs3820250_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs3820250_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs3766964_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs3766964_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs3753702_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs3753702_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs3766969_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs3766969_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs11805709_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs11805709_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs12122126_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs12122126_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs6426440_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs6426440_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs12094945_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs12094945_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2031246_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2031246_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs12034557_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs12034557_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs10915670_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs10915670_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs12035499_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs12035499_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs6666453_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs6666453_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs10915683_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs10915683_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs9426468_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs9426468_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs7518523_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs7518523_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs7541612_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs7541612_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs6683624_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs6683624_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs10158288_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs10158288_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs10915310_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs10915310_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2169089_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2169089_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs6603832_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs6603832_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs6680801_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs6680801_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs6671889_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs6671889_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs10492923_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs10492923_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs10492925_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs10492925_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs16840051_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs16840051_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs12135834_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs12135834_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs16840287_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs16840287_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs16840289_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs16840289_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs12089315_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs12089315_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs499416_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs499416_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs536995_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs536995_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs10492935_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs10492935_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs17423547_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs17423547_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs9439550_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs9439550_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs7364349_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs7364349_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs7418357_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs7418357_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2071957_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2071957_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2153900_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2153900_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs7522344_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs7522344_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs1775420_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs1775420_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs10907200_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs10907200_A  '; run;
data mx_all; set mx_all mx; run;
