ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs11131170_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs11131170_C  '; run;
data mx_all; set mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4594610_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4594610_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs13086203_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs13086203_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs7631088_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs7631088_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs1504058_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs1504058_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs1504070_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs1504070_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2047887_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2047887_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4324457_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4324457_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs3772369_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs3772369_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs17034780_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs17034780_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs1499097_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs1499097_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs6442271_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs6442271_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs3772341_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs3772341_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs3772337_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs3772337_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs3772324_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs3772324_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs10510169_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs10510169_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs10510207_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs10510207_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs265785_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs265785_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2055738_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2055738_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs17038032_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs17038032_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs17785924_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs17785924_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs7645887_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs7645887_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs3765098_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs3765098_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs155390_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs155390_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4684146_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4684146_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs17038463_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs17038463_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs155882_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs155882_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs17039604_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs17039604_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs17193526_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs17193526_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs6442451_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs6442451_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs11128727_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs11128727_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs1969290_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs1969290_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs443052_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs443052_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs440961_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs440961_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs12490663_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs12490663_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs280791_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs280791_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2648447_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2648447_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs449622_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs449622_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs459439_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs459439_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs1317443_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs1317443_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4410431_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4410431_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4684296_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4684296_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs7648926_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs7648926_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs6808990_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs6808990_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4597690_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4597690_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs8179883_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs8179883_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs7647217_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs7647217_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4365613_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4365613_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2029359_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2029359_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs6442701_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs6442701_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs12637547_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs12637547_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs1825946_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs1825946_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs11710889_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs11710889_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs10510222_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs10510222_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs6763575_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs6763575_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs17786584_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs17786584_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4593008_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4593008_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs9878112_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs9878112_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4434131_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4434131_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs17786608_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs17786608_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs17006968_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs17006968_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4129976_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4129976_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4685485_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4685485_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs17194140_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs17194140_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs1523320_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs1523320_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs984085_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs984085_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs6785626_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs6785626_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs11926996_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs11926996_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs3856841_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs3856841_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs9854419_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs9854419_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2648690_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2648690_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs749613_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs749613_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs13081043_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs13081043_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs12715075_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs12715075_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs1466459_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs1466459_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2619566_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2619566_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs17564391_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs17564391_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4553961_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4553961_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs9819935_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs9819935_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs17017790_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs17017790_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs1479544_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs1479544_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs9942085_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs9942085_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2675308_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2675308_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2728020_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2728020_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs1516398_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs1516398_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs9811943_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs9811943_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs7645216_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs7645216_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2728047_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2728047_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs12494838_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs12494838_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4642106_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4642106_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs1474021_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs1474021_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs956764_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs956764_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs2728090_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs2728090_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs1400207_C =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs1400207_C  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs4685575_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs4685575_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs6779224_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs6779224_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs6789338_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs6789338_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs34063866_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs34063866_A  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs344405_G =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs344405_G  '; run;
data mx_all; set mx_all mx; run;
ods listing close;
proc mixed data=temp method=ml noitprint noclprint ratio covtest;      class replicate pair; by replicate;      model rs17648337_A =eig1 eig2 eig3 eig4 eig5 eig6 eig7/s notest;      repeated /type=ar(1) subject=pair; ods output CovParms=mx; run; 
ods listing;
data mx; set mx; snp=' rs17648337_A  '; run;
data mx_all; set mx_all mx; run;
